name: Build and Deploy
on:
  push:
    branches:
      - main    // ここでmainブランチにpushされた時にgithubActionsがトリガーされるよと定義している

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest    // githubActionsがどんな環境で動くか指定。今回はビルドしてEC2へのデプロイができればいいのでubuntuにしておきます。

    steps:
      - name: Checkout code
        uses: actions/checkout@v2    // おまじない。githubActions上でこのリポジトリのコード使うよ～とチェックアウトする…みたいな意味らしい。

