name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd 【package.jsonまでのパス】
          npm install

      - name: Build
        run: |
          cd 【package.jsonまでのパス】
          npm run build
          
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.GIT_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST_NAME }}
          USER: ${{ secrets.EC2_USER_NAME }}
        run: |
          cd 【package.jsonまでのパス】
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key -r ./out $USER@$HOST:/var/www
          rm -f private_key

